name: Build LaTex with Nix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v31
        # Docs on https://github.com/marketplace/actions/install-nix
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: |
          nix build
          mkdir -p release
          cp result/lucas_alves_de_lima.pdf release/lucas_alves_de_lima.pdf

      - uses: actions/upload-artifact@v4
        with:
          path: release/lucas_alves_de_lima.pdf
